dist: bionic
language: php
php:
  - 7.2
  - 7.3
services:
  - mysql
cache:
  directories:
    - vendor
before_script:
  - cp .env.travis .env
  - sudo mysql -e 'create database homestead;'
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate
  - php artisan migrate
script:
  - vendor/bin/phpunit

notifications:
  email:
    recipients:
      - deardenj@uwindsor.ca
      - moore12w@uwindsor.ca
      - ouell117@uwindsor.ca
      - verma11@uwindsor.ca
    on_success: always
    on_failure: always
